### ISSUE TITLE
llvm pass

### ISSUE THREAD

**Issue by Familyye** [Saint-Theana/ollvm-ndk-android#1]
请问使用的是哪个pass呀这个r25的好像只支持4件套呀,可否添加其他的pass呢

**Comment by Saint-Theana** [comment]
估计要重新编译，编译这玩意太耗时，我用835编译的搞一次要两三天。
你自己找教程去编译吧。

**Comment by Saint-Theana** [comment]
https://github.com/bluesadi/Pluto
我记得好像是用的这个，不太记得了，可能是。
